sonar.projectKey=horarios_crud
sonar.projectName=horarios_crud
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=*/node_modules/,/dist/,/.module.ts

sonar.tests=src
sonar.test.inclusions=*/.spec.ts

sonar.sourceEncoding=UTF-8